-- CreateEnum
CREATE TYPE "UserType" AS ENUM ('AUTHOR', 'HELPER', 'OTHER');

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "lastMsgAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastMsgBy" "UserType" NOT NULL DEFAULT 'AUTHOR';
